"""
Module for parsing JSON file generated by the web scraper.
"""
import json


class Parser:

    def __init__(self):
        pass

    def parse(self, json_file_path: str) -> list:
        """
        Parses the JSON file and returns a list of data relevant to each url.
        """
        with open(json_file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
